### ISSUE TITLE
Reset Points

### ISSUE THREAD

**Issue by breakthetargets** [MakingStan/Skill-Generator#1]
Is it possible to include a reset points option (perhaps with a confirm dialogue for those who might accidentally hit it)? I didn't realize that points were a thing so I was going through the tasks to see what gets generated, and now I'm stuck with a certain amount of points.

**Comment by MakingStan** [comment]
Hey yes i would definitely be able to implement a reset button for points. If you want to reset your points you would be able to go to the .runelite directory on your machine. And then you will see a file called "Bored" in this file you could remove the existing numbers and write "0" to start over again. But in the next update i wil definitly include a reset button!

**Comment by breakthetargets** [comment]
Closing as it's been added.
